# Welcome to the Data Science Coding Challange!

Test your skills in a real-world coding challenge. Coding Challenges provide CS & DS Coding Competitions with Prizes and achievement badges!

CS & DS learners want to be challenged as a way to evaluate if they’re job ready. So, why not create fun challenges and give winners something truly valuable such as complimentary access to select Data Science courses, or the ability to receive an achievement badge on their Coursera Skills Profile - highlighting their performance to recruiters.

## Introduction

In this challenge, you'll get the opportunity to tackle one of the most industry-relevant maching learning problems with a unique dataset that will put your modeling skills to the test. Subscription services are leveraged by companies across many industries, from fitness to video streaming to retail. One of the primary objectives of companies with subscription services is to decrease churn and ensure that users are retained as subscribers. In order to do this efficiently and systematically, many companies employ machine learning to predict which users are at the highest risk of churn, so that proper interventions can be effectively deployed to the right audience.

In this challenge, we will be tackling the churn prediction problem on a very unique and interesting group of subscribers on a video streaming service!

Imagine that you are a new data scientist at this video streaming company and you are tasked with building a model that can predict which existing subscribers will continue their subscriptions for another month. We have provided a dataset that is a sample of subscriptions that were initiated in 2021, all snapshotted at a particular date before the subscription was cancelled. Subscription cancellation can happen for a multitude of reasons, including:
* the customer completes all content they were interested in, and no longer need the subscription
* the customer finds themselves to be too busy and cancels their subscription until a later time
* the customer determines that the streaming service is not the best fit for them, so they cancel and look for something better suited

Regardless the reason, this video streaming company has a vested interest in understanding the likelihood of each individual customer to churn in their subscription so that resources can be allocated appropriately to support customers. In this challenge, you will use your machine learning toolkit to do just that!

### Dataset descriptions
Both `train.csv` and `test.csv` contain one row for each unique subscription. For each subscription, a single observation (`CustomerID`) is included during which the subscription was active.

In addition to this identifier column, the `train.csv` dataset also contains the target label for the task, a binary column `Churn`.

Besides that column, both datasets have an identical set of features that can be used to train your model to make predictions. Below you can see descriptions of each feature. Familiarize yourself with them so that you can harness them most effectively for this machine learning task!

In [10]:
#Mount
%cd /content/drive/My\ Drive/work

import pandas as pd
data_descriptions = pd.read_csv('data_descriptions.csv')
pd.set_option('display.max_colwidth', None)
data_descriptions

/content/drive/My Drive/work

,Column_name,Column_type,Data_type,Description
0,AccountAge,Feature,integer,The age of the user's account in months.
1,MonthlyCharges,Feature,float,The amount charged to the user on a monthly basis.
2,TotalCharges,Feature,float,The total charges incurred by the user over the account's lifetime.
3,SubscriptionType,Feature,object,"The type of subscription chosen by the user (Basic, Standard, or Premium)."
4,PaymentMethod,Feature,string,The method of payment used by the user.
5,PaperlessBilling,Feature,string,Indicates whether the user has opted for paperless billing (Yes or No).
6,ContentType,Feature,string,"The type of content preferred by the user (Movies, TV Shows, or Both)."
7,MultiDeviceAccess,Feature,string,Indicates whether the user has access to the service on multiple devices (Yes or No).
8,DeviceRegistered,Feature,string,"The type of device registered by the user (TV, Mobile, Tablet, or Computer)."
9,ViewingHoursPerWeek,Feature,float,The number of hours the user spends watching content per week.
10,AverageViewingDuration,Feature,float,The average duration of each viewing session in minutes.
11,ContentDownloadsPerMonth,Feature,integer,The number of content downloads by the user per month.
12,GenrePreference,Feature,string,The preferred genre of content chosen by the user.
13,UserRating,Feature,float,The user's rating for the service on a scale of 1 to 5.
14,SupportTicketsPerMonth,Feature,integer,The number of support tickets raised by the user per month.
15,Gender,Feature,string,The gender of the user (Male or Female).
16,WatchlistSize,Feature,float,The number of items in the user's watchlist.
17,ParentalControl,Feature,string,Indicates whether parental control is enabled for the user (Yes or No).
18,SubtitlesEnabled,Feature,string,Indicates whether subtitles are enabled for the user (Yes or No).
19,CustomerID,Identifier,string,A unique identifier for each customer.
20,Churn,Target,integer,"The target variable indicating whether a user has churned or not (1 for churned, 0 for not churned)."

In [11]:
# Import required packages

# Data packages
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline
import tensorflow as tf
import tensorflow_decision_forests as tfdf
import sys
import IPython
from IPython import display
import sklearn
import random
import time

## Load the Data

Let's start by loading the dataset `train.csv` into a dataframe `train_df`, and `test.csv` into a dataframe `test_df` and display the shape of the dataframes.

In [12]:
train_df = pd.read_csv("train.csv")
print('train_df Shape:', train_df.shape)
train_df.head()

train_df Shape: (243787, 21)

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,...,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,CustomerID,Churn
0,20,11.055215,221.104302,Premium,Mailed check,No,Both,No,Mobile,36.758104,...,10,Sci-Fi,2.176498,4,Male,3,No,No,CB6SXPNVZA,0
1,57,5.175208,294.986882,Basic,Credit card,Yes,Movies,No,Tablet,32.450568,...,18,Action,3.478632,8,Male,23,No,Yes,S7R2G87O09,0
2,73,12.106657,883.785952,Basic,Mailed check,Yes,Movies,No,Computer,7.395160,...,23,Fantasy,4.238824,6,Male,1,Yes,Yes,EASDC20BDT,0
3,32,7.263743,232.439774,Basic,Electronic check,No,TV Shows,No,Tablet,27.960389,...,30,Drama,4.276013,2,Male,24,Yes,Yes,NPF69NT69N,0
4,57,16.953078,966.325422,Premium,Electronic check,Yes,TV Shows,No,TV,20.083397,...,20,Comedy,3.616170,4,Female,0,No,No,4LGYPK7VOL,0

In [13]:
test_df = pd.read_csv("test.csv")
print('test_df Shape:', test_df.shape)
CustomerID=test_df['CustomerID']
test_df.head()

test_df Shape: (104480, 20)

,AccountAge,MonthlyCharges,TotalCharges,SubscriptionType,PaymentMethod,PaperlessBilling,ContentType,MultiDeviceAccess,DeviceRegistered,ViewingHoursPerWeek,AverageViewingDuration,ContentDownloadsPerMonth,GenrePreference,UserRating,SupportTicketsPerMonth,Gender,WatchlistSize,ParentalControl,SubtitlesEnabled,CustomerID
0,38,17.869374,679.036195,Premium,Mailed check,No,TV Shows,No,TV,29.126308,122.274031,42,Comedy,3.522724,2,Male,23,No,No,O1W6BHP6RM
1,77,9.912854,763.289768,Basic,Electronic check,Yes,TV Shows,No,TV,36.873729,57.093319,43,Action,2.021545,2,Female,22,Yes,No,LFR4X92X8H
2,5,15.019011,75.095057,Standard,Bank transfer,No,TV Shows,Yes,Computer,7.601729,140.414001,14,Sci-Fi,4.806126,2,Female,22,No,Yes,QM5GBIYODA
3,88,15.357406,1351.451692,Standard,Electronic check,No,Both,Yes,Tablet,35.586430,177.002419,14,Comedy,4.943900,0,Female,23,Yes,Yes,D9RXTK2K9F
4,91,12.406033,1128.949004,Standard,Credit card,Yes,TV Shows,Yes,Tablet,23.503651,70.308376,6,Drama,2.846880,6,Female,0,No,No,ENTCCHR1LR

## Make predictions (required)

Remember you should create a dataframe named `prediction_df` with exactly 104,480 entries plus a header row attempting to predict the likelihood of churn for subscriptions in `test_df`. Your submission will throw an error if you have extra columns (beyond `CustomerID` and `predicted_probaility`) or extra rows.

The file should have exactly 2 columns:
`CustomerID` (sorted in any order)
`predicted_probability` (contains your numeric predicted probabilities between 0 and 1, e.g. from `estimator.predict_proba(X, y)[:, 1]`)

The naming convention of the dataframe and columns are critical for our autograding, so please make sure to use the exact naming conventions of `prediction_df` with column names `CustomerID` and `predicted_probability`!

### Example prediction submission:

The code below is a very naive prediction method that simply predicts churn using a Dummy Classifier. This is used as just an example showing the submission format required. Please change/alter/delete this code below and create your own improved prediction methods for generating `prediction_df`.

**PLEASE CHANGE CODE BELOW TO IMPLEMENT YOUR OWN PREDICTIONS**

In [14]:
train_df=train_df.dropna()
test_df=test_df.dropna()
train_df=tfdf.keras.pd_dataframe_to_tf_dataset(train_df,label="Churn")
test_df=tfdf.keras.pd_dataframe_to_tf_dataset(test_df)

In [15]:
model=tfdf.keras.GradientBoostedTreesModel()
model.fit(train_df)
print(model.summary())

Use /tmp/tmp9zsfffdq as temporary training directory
Reading training dataset...
Training dataset read in 0:00:06.505391. Found 243787 examples.
Training model...
Model trained in 0:00:22.804466
Compiling model...
Model compiled.
Model: "gradient_boosted_trees_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
=================================================================
Total params: 1 (1.00 Byte)
Trainable params: 0 (0.00 Byte)
Non-trainable params: 1 (1.00 Byte)
_________________________________________________________________
Type: "GRADIENT_BOOSTED_TREES"
Task: CLASSIFICATION
Label: "__LABEL"

Input Features (20):
	AccountAge
	AverageViewingDuration
	ContentDownloadsPerMonth
	ContentType
	CustomerID
	DeviceRegistered
	Gender
	GenrePreference
	MonthlyCharges
	MultiDeviceAccess
	PaperlessBilling
	ParentalControl
	PaymentMethod
	SubscriptionType
	SubtitlesEnabled
	SupportTicketsPerMonth
	TotalCharges
	UserRating
	ViewingHoursPerWeek
	WatchlistSize

No weights

Variable Importance: INV_MEAN_MIN_DEPTH:
    1.               "AccountAge"  0.259994 ################
    2.   "AverageViewingDuration"  0.247229 #############
    3.      "ViewingHoursPerWeek"  0.228686 ##########
    4. "ContentDownloadsPerMonth"  0.219573 ########
    5.   "SupportTicketsPerMonth"  0.217517 ########
    6.           "MonthlyCharges"  0.206794 ######
    7.         "SubscriptionType"  0.199539 #####
    8.          "GenrePreference"  0.196110 ####
    9.            "PaymentMethod"  0.194661 ####
   10.               "UserRating"  0.183167 ##
   11.             "TotalCharges"  0.178126 #
   12.            "WatchlistSize"  0.177848 #
   13.         "SubtitlesEnabled"  0.175236 #
   14.              "ContentType"  0.174114 #
   15.         "DeviceRegistered"  0.169936
   16.                   "Gender"  0.169104
   17.          "ParentalControl"  0.168753
   18.        "MultiDeviceAccess"  0.167775
   19.         "PaperlessBilling"  0.167717

Variable Importance: NUM_AS_ROOT:
    1.               "AccountAge" 26.000000 ################
    2.         "SubscriptionType" 13.000000 #######
    3.   "SupportTicketsPerMonth" 12.000000 #######
    4.          "GenrePreference" 11.000000 ######
    5.            "PaymentMethod" 10.000000 #####
    6. "ContentDownloadsPerMonth"  5.000000 ##
    7.      "ViewingHoursPerWeek"  3.000000 #
    8.   "AverageViewingDuration"  2.000000
    9.           "MonthlyCharges"  2.000000
   10.         "SubtitlesEnabled"  2.000000
   11.              "ContentType"  1.000000

Variable Importance: NUM_NODES:
    1.      "ViewingHoursPerWeek" 408.000000 ################
    2.           "MonthlyCharges" 382.000000 ##############
    3.   "AverageViewingDuration" 373.000000 ##############
    4. "ContentDownloadsPerMonth" 290.000000 ###########
    5.               "AccountAge" 245.000000 #########
    6.               "UserRating" 206.000000 ########
    7.   "SupportTicketsPerMonth" 166.000000 ######
    8.             "TotalCharges" 152.000000 #####
    9.            "WatchlistSize" 89.000000 ###
   10.          "GenrePreference" 69.000000 ##
   11.            "PaymentMethod" 63.000000 ##
   12.         "SubscriptionType" 55.000000 ##
   13.              "ContentType" 31.000000 #
   14.         "DeviceRegistered" 22.000000
   15.         "SubtitlesEnabled" 16.000000
   16.                   "Gender" 10.000000
   17.          "ParentalControl" 10.000000
   18.        "MultiDeviceAccess"  2.000000
   19.         "PaperlessBilling"  2.000000

Variable Importance: SUM_SCORE:
    1.               "AccountAge" 7156.457342 ################
    2.   "AverageViewingDuration" 4384.273217 #########
    3.      "ViewingHoursPerWeek" 3754.070053 ########
    4. "ContentDownloadsPerMonth" 3479.733389 #######
    5.           "MonthlyCharges" 2435.492975 #####
    6.   "SupportTicketsPerMonth" 1470.499464 ###
    7.               "UserRating" 340.955612
    8.         "SubscriptionType" 264.485359
    9.             "TotalCharges" 220.625334
   10.            "PaymentMethod" 219.246301
   11.            "WatchlistSize" 167.842656
   12.          "GenrePreference" 159.506595
   13.              "ContentType" 57.738332
   14.         "DeviceRegistered" 24.803676
   15.         "SubtitlesEnabled" 23.643008
   16.                   "Gender" 14.287447
   17.          "ParentalControl" 12.670316
   18.         "PaperlessBilling"  2.769702
   19.        "MultiDeviceAccess"  1.669871



Loss: BINOMIAL_LOG_LIKELIHOOD
Validation loss value: 0.825415
Number of trees per iteration: 1
Node format: NOT_SET
Number of trees: 87
Total number of nodes: 5269

Number of nodes by tree:
Count: 87 Average: 60.5632 StdDev: 4.03918
Min: 45 Max: 63 Ignored: 0
----------------------------------------------
[ 45, 46)  1   1.15%   1.15%
[ 46, 47)  0   0.00%   1.15%
[ 47, 48)  1   1.15%   2.30%
[ 48, 49)  0   0.00%   2.30%
[ 49, 50)  0   0.00%   2.30%
[ 50, 51)  0   0.00%   2.30%
[ 51, 52)  4   4.60%   6.90% #
[ 52, 53)  0   0.00%   6.90%
[ 53, 54)  3   3.45%  10.34% #
[ 54, 55)  0   0.00%  10.34%
[ 55, 56)  3   3.45%  13.79% #
[ 56, 57)  0   0.00%  13.79%
[ 57, 58)  4   4.60%  18.39% #
[ 58, 59)  0   0.00%  18.39%
[ 59, 60)  5   5.75%  24.14% #
[ 60, 61)  0   0.00%  24.14%
[ 61, 62) 16  18.39%  42.53% ###
[ 62, 63)  0   0.00%  42.53%
[ 63, 63] 50  57.47% 100.00% ##########

Depth by leafs:
Count: 2678 Average: 4.96789 StdDev: 0.21452
Min: 3 Max: 5 Ignored: 0
----------------------------------------------
[ 3, 4)   20   0.75%   0.75%
[ 4, 5)   46   1.72%   2.46%
[ 5, 5] 2612  97.54% 100.00% ##########

Number of training obs by leaf:
Count: 2678 Average: 7123.83 StdDev: 12442.6
Min: 5 Max: 134875 Ignored: 0
----------------------------------------------
[      5,   6748) 1870  69.83%  69.83% ##########
[   6748,  13492)  403  15.05%  84.88% ##
[  13492,  20235)  153   5.71%  90.59% #
[  20235,  26979)   89   3.32%  93.91%
[  26979,  33722)   44   1.64%  95.56%
[  33722,  40466)   42   1.57%  97.12%
[  40466,  47209)   23   0.86%  97.98%
[  47209,  53953)   20   0.75%  98.73%
[  53953,  60696)    6   0.22%  98.95%
[  60696,  67440)    9   0.34%  99.29%
[  67440,  74184)    5   0.19%  99.48%
[  74184,  80927)    4   0.15%  99.63%
[  80927,  87671)    2   0.07%  99.70%
[  87671,  94414)    1   0.04%  99.74%
[  94414, 101158)    2   0.07%  99.81%
[ 101158, 107901)    2   0.07%  99.89%
[ 107901, 114645)    0   0.00%  99.89%
[ 114645, 121388)    2   0.07%  99.96%
[ 121388, 128132)    0   0.00%  99.96%
[ 128132, 134875]    1   0.04% 100.00%

Attribute in nodes:
	408 : ViewingHoursPerWeek [NUMERICAL]
	382 : MonthlyCharges [NUMERICAL]
	373 : AverageViewingDuration [NUMERICAL]
	290 : ContentDownloadsPerMonth [NUMERICAL]
	245 : AccountAge [NUMERICAL]
	206 : UserRating [NUMERICAL]
	166 : SupportTicketsPerMonth [NUMERICAL]
	152 : TotalCharges [NUMERICAL]
	89 : WatchlistSize [NUMERICAL]
	69 : GenrePreference [CATEGORICAL]
	63 : PaymentMethod [CATEGORICAL]
	55 : SubscriptionType [CATEGORICAL]
	31 : ContentType [CATEGORICAL]
	22 : DeviceRegistered [CATEGORICAL]
	16 : SubtitlesEnabled [CATEGORICAL]
	10 : ParentalControl [CATEGORICAL]
	10 : Gender [CATEGORICAL]
	2 : PaperlessBilling [CATEGORICAL]
	2 : MultiDeviceAccess [CATEGORICAL]

Attribute in nodes with depth <= 0:
	26 : AccountAge [NUMERICAL]
	13 : SubscriptionType [CATEGORICAL]
	12 : SupportTicketsPerMonth [NUMERICAL]
	11 : GenrePreference [CATEGORICAL]
	10 : PaymentMethod [CATEGORICAL]
	5 : ContentDownloadsPerMonth [NUMERICAL]
	3 : ViewingHoursPerWeek [NUMERICAL]
	2 : SubtitlesEnabled [CATEGORICAL]
	2 : MonthlyCharges [NUMERICAL]
	2 : AverageViewingDuration [NUMERICAL]
	1 : ContentType [CATEGORICAL]

Attribute in nodes with depth <= 1:
	51 : AverageViewingDuration [NUMERICAL]
	39 : AccountAge [NUMERICAL]
	27 : ViewingHoursPerWeek [NUMERICAL]
	26 : SupportTicketsPerMonth [NUMERICAL]
	23 : ContentDownloadsPerMonth [NUMERICAL]
	19 : SubscriptionType [CATEGORICAL]
	16 : PaymentMethod [CATEGORICAL]
	16 : GenrePreference [CATEGORICAL]
	15 : MonthlyCharges [NUMERICAL]
	8 : UserRating [NUMERICAL]
	7 : SubtitlesEnabled [CATEGORICAL]
	5 : WatchlistSize [NUMERICAL]
	4 : TotalCharges [NUMERICAL]
	4 : ContentType [CATEGORICAL]
	1 : Gender [CATEGORICAL]

Attribute in nodes with depth <= 2:
	104 : ViewingHoursPerWeek [NUMERICAL]
	104 : AverageViewingDuration [NUMERICAL]
	64 : AccountAge [NUMERICAL]
	63 : ContentDownloadsPerMonth [NUMERICAL]
	60 : MonthlyCharges [NUMERICAL]
	50 : SupportTicketsPerMonth [NUMERICAL]
	24 : PaymentMethod [CATEGORICAL]
	23 : TotalCharges [NUMERICAL]
	23 : GenrePreference [CATEGORICAL]
	22 : SubscriptionType [CATEGORICAL]
	21 : UserRating [NUMERICAL]
	19 : WatchlistSize [NUMERICAL]
	10 : SubtitlesEnabled [CATEGORICAL]
	10 : ContentType [CATEGORICAL]
	7 : DeviceRegistered [CATEGORICAL]
	3 : ParentalControl [CATEGORICAL]
	2 : Gender [CATEGORICAL]

Attribute in nodes with depth <= 3:
	213 : ViewingHoursPerWeek [NUMERICAL]
	197 : AverageViewingDuration [NUMERICAL]
	163 : MonthlyCharges [NUMERICAL]
	159 : ContentDownloadsPerMonth [NUMERICAL]
	122 : AccountAge [NUMERICAL]
	89 : SupportTicketsPerMonth [NUMERICAL]
	83 : UserRating [NUMERICAL]
	59 : TotalCharges [NUMERICAL]
	44 : WatchlistSize [NUMERICAL]
	35 : GenrePreference [CATEGORICAL]
	33 : PaymentMethod [CATEGORICAL]
	30 : SubscriptionType [CATEGORICAL]
	20 : ContentType [CATEGORICAL]
	13 : SubtitlesEnabled [CATEGORICAL]
	10 : DeviceRegistered [CATEGORICAL]
	7 : ParentalControl [CATEGORICAL]
	7 : Gender [CATEGORICAL]
	1 : MultiDeviceAccess [CATEGORICAL]

Attribute in nodes with depth <= 5:
	408 : ViewingHoursPerWeek [NUMERICAL]
	382 : MonthlyCharges [NUMERICAL]
	373 : AverageViewingDuration [NUMERICAL]
	290 : ContentDownloadsPerMonth [NUMERICAL]
	245 : AccountAge [NUMERICAL]
	206 : UserRating [NUMERICAL]
	166 : SupportTicketsPerMonth [NUMERICAL]
	152 : TotalCharges [NUMERICAL]
	89 : WatchlistSize [NUMERICAL]
	69 : GenrePreference [CATEGORICAL]
	63 : PaymentMethod [CATEGORICAL]
	55 : SubscriptionType [CATEGORICAL]
	31 : ContentType [CATEGORICAL]
	22 : DeviceRegistered [CATEGORICAL]
	16 : SubtitlesEnabled [CATEGORICAL]
	10 : ParentalControl [CATEGORICAL]
	10 : Gender [CATEGORICAL]
	2 : PaperlessBilling [CATEGORICAL]
	2 : MultiDeviceAccess [CATEGORICAL]

Condition type in nodes:
	2311 : HigherCondition
	280 : ContainsBitmapCondition
Condition type in nodes with depth <= 0:
	50 : HigherCondition
	37 : ContainsBitmapCondition
Condition type in nodes with depth <= 1:
	198 : HigherCondition
	63 : ContainsBitmapCondition
Condition type in nodes with depth <= 2:
	508 : HigherCondition
	101 : ContainsBitmapCondition
Condition type in nodes with depth <= 3:
	1129 : HigherCondition
	156 : ContainsBitmapCondition
Condition type in nodes with depth <= 5:
	2311 : HigherCondition
	280 : ContainsBitmapCondition

Training logs:
Number of iteration to final model: 87
	Iter:1 train-loss:0.929557 valid-loss:0.931558  train-accuracy:0.818828 valid-accuracy:0.818234
	Iter:2 train-loss:0.916263 valid-loss:0.918247  train-accuracy:0.818828 valid-accuracy:0.818234
	Iter:3 train-loss:0.905148 valid-loss:0.906977  train-accuracy:0.818828 valid-accuracy:0.818234
	Iter:4 train-loss:0.895910 valid-loss:0.898002  train-accuracy:0.818828 valid-accuracy:0.818234
	Iter:5 train-loss:0.888027 valid-loss:0.890409  train-accuracy:0.818828 valid-accuracy:0.818234
	Iter:6 train-loss:0.881392 valid-loss:0.884092  train-accuracy:0.818828 valid-accuracy:0.818234
	Iter:16 train-loss:0.844392 valid-loss:0.848986  train-accuracy:0.820305 valid-accuracy:0.819621
	Iter:26 train-loss:0.830084 valid-loss:0.836664  train-accuracy:0.822877 valid-accuracy:0.821376
	Iter:36 train-loss:0.822510 valid-loss:0.831015  train-accuracy:0.824090 valid-accuracy:0.822682
	Iter:46 train-loss:0.817621 valid-loss:0.828001  train-accuracy:0.824957 valid-accuracy:0.823008
	Iter:56 train-loss:0.814149 valid-loss:0.826685  train-accuracy:0.825618 valid-accuracy:0.822927
	Iter:66 train-loss:0.811526 valid-loss:0.825843  train-accuracy:0.826183 valid-accuracy:0.823049
	Iter:76 train-loss:0.809426 valid-loss:0.825579  train-accuracy:0.826576 valid-accuracy:0.823294
	Iter:86 train-loss:0.807695 valid-loss:0.825458  train-accuracy:0.827000 valid-accuracy:0.823008
	Iter:96 train-loss:0.806124 valid-loss:0.825547  train-accuracy:0.827392 valid-accuracy:0.822886
	Iter:106 train-loss:0.804629 valid-loss:0.825581  train-accuracy:0.827816 valid-accuracy:0.822560
	Iter:116 train-loss:0.803432 valid-loss:0.825751  train-accuracy:0.828035 valid-accuracy:0.822315

None

In [16]:
self_evaluation = model.make_inspector().evaluation()
print(f"Accuracy: {self_evaluation.accuracy} Loss:{self_evaluation.loss}")

Accuracy: 0.8229677081108093 Loss:0.8254150152206421

In [27]:
tuner = tfdf.tuner.RandomSearch(num_trials=12)  # Adjusted number of trials

# Simplified search space
tuner.choice("min_examples", [5, 10])
tuner.choice("max_depth", [3, 6])

tuner.choice("shrinkage", [0.05, 0.10])
tuner.choice("num_candidate_attributes_ratio", [0.5, 1.0])

# Use a simplified version for "split_axis"
tuner.choice("split_axis", ["AXIS_ALIGNED"])

# Tuning the model with the specified tuner
tuned_model = tfdf.keras.GradientBoostedTreesModel(tuner=tuner)
tuned_model.fit(train_df, verbose=0)

# Evaluation
tuned_self_evaluation = tuned_model.make_inspector().evaluation()
print(f"Accuracy: {tuned_self_evaluation.accuracy} Loss:{tuned_self_evaluation.loss}")

Use /tmp/tmpcnqtca59 as temporary training directory
Accuracy: 0.8237022757530212 Loss:0.8242841958999634

In [28]:
prediction_tuned=tuned_model.predict(test_df)
prediction_tuned = prediction.flatten()

105/105 [==============================] - 1s 9ms/step

In [29]:
submission = pd.DataFrame({'CustomerID': CustomerID, 'predicted_probability': prediction_tuned})
submission.to_csv("prediction_submission.csv",index=False)