In [2]:
#get the data from the polygon api
import requests     
import json
import csv
import datetime
import os
import time

url="https://api.polygon.io/v2/aggs/ticker/AMD/range/1000/second/2024-03-07/2024-03-08?adjusted=true&sort=asc&limit=50000&apiKey=I3jwnNbug0UkFs3G78dNjo2LNlI4Xu9G"

In [6]:
url="https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/day/2023-01-09/2023-01-09?apiKey=I3jwnNbug0UkFs3G78dNjo2LNlI4Xu9G"

response = requests.get(url)
data = response.json()

In [7]:
data

{'ticker': 'AAPL',
 'queryCount': 1,
 'resultsCount': 1,
 'adjusted': True,
 'results': [{'v': 70790813.0,
   'vw': 131.6292,
   'o': 130.465,
   'c': 130.15,
   'h': 133.41,
   'l': 129.89,
   't': 1673240400000,
   'n': 645365}],
 'status': 'OK',
 'request_id': '917f1ec553b980a2a5628123c3e207a1',
 'count': 1}

In [37]:
data=requests.get("https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2024-03-07/2024-03-07?adjusted=true&sort=asc&limit=1000&apiKey=I3jwnNbug0UkFs3G78dNjo2LNlI4Xu9G").json()
import pandas as pd
df=pd.DataFrame(data['results'])
df

#change Unix time to date time
df['t']=pd.to_datetime(df['t'],unit='ms')
df
#drop outside of trading out
df=df[df['t'].dt.time.between(datetime.time(9,30),datetime.time(16,0))]
df

,v,vw,o,c,h,l,t,n
23,946.0,168.4953,168.5000,168.5000,168.50,168.50,2024-03-07 09:30:00,42
24,737.0,168.5037,168.4900,168.4900,168.49,168.49,2024-03-07 09:31:00,27
25,2065.0,168.3661,168.4500,168.3000,168.45,168.30,2024-03-07 09:32:00,88
26,1822.0,168.3213,168.3300,168.3000,168.33,168.30,2024-03-07 09:34:00,29
27,1893.0,168.2754,168.3000,168.2900,168.30,168.29,2024-03-07 09:35:00,72
...,...,...,...,...,...,...,...,...
345,126666.0,168.6558,168.6800,168.6175,168.71,168.61,2024-03-07 15:56:00,2736
346,114040.0,168.6987,168.6267,168.7100,168.74,168.62,2024-03-07 15:57:00,2584
347,116052.0,168.7049,168.7100,168.6874,168.75,168.68,2024-03-07 15:58:00,2847
348,116936.0,168.7287,168.6885,168.7800,168.78,168.68,2024-03-07 15:59:00,3670
349,150011.0,168.7792,168.7750,168.7650,168.81,168.75,2024-03-07 16:00:00,3797

In [34]:
import yfinance as yf


df=yf.download("AAPL",start="2024-03-07",end="2024-03-08", interval="1m")
df

[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Datetime,,,,,,
2024-03-07 09:30:00-05:00,169.149994,169.330002,168.669998,168.690002,168.690002,3173932
2024-03-07 09:31:00-05:00,168.684998,168.924606,168.610001,168.720001,168.720001,381598
2024-03-07 09:32:00-05:00,168.720001,169.350006,168.679993,169.179993,169.179993,413468
2024-03-07 09:33:00-05:00,169.175995,169.629303,169.160004,169.380005,169.380005,337229
2024-03-07 09:34:00-05:00,169.369995,169.740005,169.360001,169.690002,169.690002,499142
...,...,...,...,...,...,...
2024-03-07 15:55:00-05:00,169.270004,169.320007,169.160004,169.199997,169.199997,401449
2024-03-07 15:56:00-05:00,169.199997,169.229996,169.110001,169.119995,169.119995,326517
2024-03-07 15:57:00-05:00,169.115005,169.130005,168.899994,169.022507,169.022507,536623
2024-03-07 15:58:00-05:00,169.020004,169.100006,168.970001,169.095001,169.095001,478816
2024-03-07 15:59:00-05:00,169.095001,169.139999,168.949997,168.979996,168.979996,1080155

In [12]:
data

[{'v': 70790813.0,
  'vw': 131.6292,
  'o': 130.465,
  'c': 130.15,
  'h': 133.41,
  'l': 129.89,
  't': 1673240400000,
  'n': 645365},
 {'v': 63896155.0,
  'vw': 129.822,
  'o': 130.26,
  'c': 130.73,
  'h': 131.2636,
  'l': 128.12,
  't': 1673326800000,
  'n': 554940},
 {'v': 69458949.0,
  'vw': 132.3081,
  'o': 131.25,
  'c': 133.49,
  'h': 133.51,
  'l': 130.46,
  't': 1673413200000,
  'n': 561278},
 {'v': 71379648.0,
  'vw': 133.171,
  'o': 133.88,
  'c': 133.41,
  'h': 134.26,
  'l': 131.44,
  't': 1673499600000,
  'n': 635331},
 {'v': 57809719.0,
  'vw': 133.6773,
  'o': 132.03,
  'c': 134.76,
  'h': 134.92,
  'l': 131.66,
  't': 1673586000000,
  'n': 537385},
 {'v': 63612627.0,
  'vw': 135.7587,
  'o': 134.83,
  'c': 135.94,
  'h': 137.29,
  'l': 134.13,
  't': 1673931600000,
  'n': 595831},
 {'v': 69672800.0,
  'vw': 136.3316,
  'o': 136.815,
  'c': 135.21,
  'h': 138.61,
  'l': 135.03,
  't': 1674018000000,
  'n': 578304},
 {'v': 58280413.0,
  'vw': 134.9653,
  'o': 134.08,
  'c': 135.27,
  'h': 136.25,
  'l': 133.77,
  't': 1674104400000,
  'n': 491674},
 {'v': 80200655.0,
  'vw': 136.3762,
  'o': 135.28,
  'c': 137.87,
  'h': 138.02,
  'l': 134.22,
  't': 1674190800000,
  'n': 552230},
 {'v': 81760313.0,
  'vw': 141.2116,
  'o': 138.12,
  'c': 141.11,
  'h': 143.315,
  'l': 137.9,
  't': 1674450000000,
  'n': 719288},
 {'v': 66435142.0,
  'vw': 142.0507,
  'o': 140.305,
  'c': 142.53,
  'h': 143.16,
  'l': 140.3,
  't': 1674536400000,
  'n': 498679},
 {'v': 65799349.0,
  'vw': 140.7526,
  'o': 140.89,
  'c': 141.86,
  'h': 142.43,
  'l': 138.81,
  't': 1674622800000,
  'n': 536505},
 {'v': 54105068.0,
  'vw': 143.3429,
  'o': 143.17,
  'c': 143.96,
  'h': 144.25,
  'l': 141.9,
  't': 1674709200000,
  'n': 472135},
 {'v': 70547743.0,
  'vw': 145.8365,
  'o': 143.155,
  'c': 145.93,
  'h': 147.23,
  'l': 143.08,
  't': 1674795600000,
  'n': 560022},
 {'v': 64015274.0,
  'vw': 143.6524,
  'o': 144.955,
  'c': 143,
  'h': 145.55,
  'l': 142.85,
  't': 1675054800000,
  'n': 551111},
 {'v': 65874459.0,
  'vw': 143.6473,
  'o': 142.7,
  'c': 144.29,
  'h': 144.34,
  'l': 142.28,
  't': 1675141200000,
  'n': 468170},
 {'v': 77663426.0,
  'vw': 143.8723,
  'o': 143.97,
  'c': 145.43,
  'h': 146.61,
  'l': 141.32,
  't': 1675227600000,
  'n': 693374},
 {'v': 118338980.0,
  'vw': 149.3764,
  'o': 148.9,
  'c': 150.82,
  'h': 151.18,
  'l': 148.17,
  't': 1675314000000,
  'n': 996203},
 {'v': 154338835.0,
  'vw': 154.2437,
  'o': 148.03,
  'c': 154.5,
  'h': 157.38,
  'l': 147.83,
  't': 1675400400000,
  'n': 1141350},
 {'v': 69771906.0,
  'vw': 152.0939,
  'o': 152.575,
  'c': 151.73,
  'h': 153.1,
  'l': 150.78,
  't': 1675659600000,
  'n': 583517},
 {'v': 83322551.0,
  'vw': 153.4202,
  'o': 150.64,
  'c': 154.65,
  'h': 155.23,
  'l': 150.64,
  't': 1675746000000,
  'n': 661767},
 {'v': 63620079.0,
  'vw': 152.3636,
  'o': 153.88,
  'c': 151.92,
  'h': 154.58,
  'l': 151.168,
  't': 1675832400000,
  'n': 524140},
 {'v': 55994243.0,
  'vw': 152.2769,
  'o': 153.775,
  'c': 150.87,
  'h': 154.33,
  'l': 150.42,
  't': 1675918800000,
  'n': 471973},
 {'v': 57388108.0,
  'vw': 150.4054,
  'o': 149.46,
  'c': 151.01,
  'h': 151.3401,
  'l': 149.22,
  't': 1676005200000,
  'n': 443405},
 {'v': 62199013.0,
  'vw': 153.231,
  'o': 150.952,
  'c': 153.85,
  'h': 154.26,
  'l': 150.92,
  't': 1676264400000,
  'n': 506668},
 {'v': 61664023.0,
  'vw': 152.5956,
  'o': 152.12,
  'c': 153.2,
  'h': 153.77,
  'l': 150.86,
  't': 1676350800000,
  'n': 528566},
 {'v': 65665252.0,
  'vw': 154.4536,
  'o': 153.11,
  'c': 155.33,
  'h': 155.5,
  'l': 152.88,
  't': 1676437200000,
  'n': 520574},
 {'v': 68167942.0,
  'vw': 154.7143,
  'o': 153.51,
  'c': 153.71,
  'h': 156.33,
  'l': 153.3475,
  't': 1676523600000,
  'n': 516187},
 {'v': 59105618.0,
  'vw': 152.0451,
  'o': 152.35,
  'c': 152.55,
  'h': 153,
  'l': 150.85,
  't': 1676610000000,
  'n': 468580},
 {'v': 58217230.0,
  'vw': 149.3501,
  'o': 150.2,
  'c': 148.48,
  'h': 151.3,
  'l': 148.405,
  't': 1676955600000,
  'n': 509342},
 {'v': 51008155.0,
  'vw': 148.5494,
  'o': 148.87,
  'c': 148.91,
  'h': 149.95,
  'l': 147.16,
  't': 1677042000000,
  'n': 429775},
 {'v': 48392049.0,
  'vw': 148.8407,
  'o': 150.09,
  'c': 149.4,
  'h': 150.34,
  'l': 147.24,
  't': 1677128400000,
  'n': 425159},
 {'v': 55469606.0,
  'vw': 146.3861,
  'o': 147.11,
  'c': 146.71,
  'h': 147.19,
  'l': 145.7202,
  't': 1677214800000,
  'n': 472221},
 {'v': 44998470.0,
  'vw': 148.1344,
  'o': 147.71,
  'c': 147.92,
  'h': 149.17,
  'l': 147.45,
  't': 1677474000000,
  'n': 418069},
 {'v': 50546998.0,
  'vw': 147.7996,
  'o': 147.05,
  'c': 147.41,
  'h': 149.08,
  'l': 146.83,
  't': 1677560400000,
  'n': 383779},
 {'v': 55478991.0,
  'vw': 145.868,
  'o': 146.83,
  'c': 145.31,
  'h': 147.2285,
  'l': 145.01,
  't': 1677646800000,
  'n': 461613},
 {'v': 52279761.0,
  'vw': 145.1652,
  'o': 144.38,
  'c': 145.91,
  'h': 146.71,
  'l': 143.9,
  't': 1677733200000,
  'n': 413238},
 {'v': 70725339.0,
  'vw': 150.0304,
  'o': 148.045,
  'c': 151.03,
  'h': 151.11,
  'l': 147.33,
  't': 1677819600000,
  'n': 558706},
 {'v': 87558028.0,
  'vw': 154.6895,
  'o': 153.785,
  'c': 153.83,
  'h': 156.3,
  'l': 153.46,
  't': 1678078800000,
  'n': 691990},
 {'v': 56136378.0,
  'vw': 152.2768,
  'o': 153.7,
  'c': 151.6,
  'h': 154.0299,
  'l': 151.13,
  't': 1678165200000,
  'n': 496631},
 {'v': 47204791.0,
  'vw': 152.6973,
  'o': 152.81,
  'c': 152.87,
  'h': 153.47,
  'l': 151.83,
  't': 1678251600000,
  'n': 405203},
 {'v': 53833122.0,
  'vw': 152.4689,
  'o': 153.559,
  'c': 150.59,
  'h': 154.535,
  'l': 150.225,
  't': 1678338000000,
  'n': 480909}]